### ISSUE TITLE
Adicionar Busca de Cidades no ConfigFlow

### ISSUE THREAD

**Issue by sigrist** [sigrist/inmet#4]
Atualmente, temos que entrar o código da cidade para configurar o plugin de alertas meteorológicos, o que pode ser confuso e difícil de localizar, especialmente se não conhecem o código exato.

Alterar o config_flow do plugin para permitir a busca de cidades por nome, utilizando a API REST fornecida pela Inmet. A funcionalidade de autocomplete simplificará o processo, permitindo que os usuários selecionem a cidade diretamente.

## Detalhes
Endpoint da API para Busca de Cidades:

URL: `https://apiprevmet3.inmet.gov.br/autocomplete/{nome_da_cidade}`
Método: `GET`
Resposta: JSON com detalhes da cidade, incluindo id, label, geocode, latitude, e longitude.

```
[
    {
        "id": "Campinas-SP",
        "label": "Campinas-SP",
        "value": "Campinas-SP",
        "custom": "SP-Campinas",
        "geocode": 3509502,
        "latitude": "-22.882993963711996",
        "longitude": "-47.0433269868823"
    },
    ...
]
```

**Comment by maimrn** [comment]
Creio ser possível fazer uma busca na tabela do IBGE:

https://www.ibge.gov.br/explica/codigos-dos-municipios.php
